### ISSUE TITLE
Should we use this or https://github.com/saltstack-formulas/arvados-formula ?

### ISSUE THREAD

**Issue by mr-c** [arvados/arvados-formula#2]

**Comment by javierbertoli** [comment]
@mr-c we documented it [here](https://doc.arvados.org/install/salt-multi-host.html#saltstack): This copy of the formula is our `development` version, while the one hosted in [saltstack-formulas](https://github.com/saltstack-formulas/arvados-formula) is the current, `production-ready` one. That said, most of the time both repos are kept in sync, so you won't notice much differences.

The reason for this choice is that most people using SaltStack formulas will try to get them from the [saltstack-formulas](https://github.com/saltstack-formulas/arvados-formula)'s repositories, so it makes sense to keep the production version of the formula there.
